### ISSUE TITLE
_match_single(): Zero matches.

### ISSUE THREAD

**Issue by ahmethakanbesel** [ffilopeter/Youtube#1]
What's wrong? I am getting this error.
<pre>_match_single(): Zero matches.</pre>
Code:
```
<?php
require __DIR__ . '/Youtube.class.php';
$url = "https://www.youtube.com/watch?v=mDldVg_ZShI";
$yt = new Youtube($url);
echo $yt->player_script;
```

**Comment by ffilopeter** [comment]
Are you sure you're not getting any other errors? 

This error says, that zero matches were found in _match_single() function. This function is called in Extractor.class.php in the private function _extract().

_match_single() function is basically just preg_match() that kills program if zero or >1 matches were found by pattern in context.

Try to var_dump the whole $yt object. The whole "system" is just two short PHP classes. Try to figure it out, if you'll have problems I will try to fix it ASAP (I'm busy now)

BTW: Youtube might done changes in way they play videos, I am not sure if it still does work this way.
